title: zhh  
description: My Personal Blog
author: Zhang Hao
logo: /kctm.github.io/static/img/avatar.png
github: https://github.com/kctm
about: Will be ok~

baseurl: ""
url: ""

allowsearch: true

##disqus_shortname: aboutashu
baidu_analytics: 0fabf3decc66f37a1590a2d6a806375f

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
